const commonObjects = [
  "airplane", "alarm clock", "ambulance", "anchor", "apple", "aquarium", "armchair",
  "arrow", "backpack", "balloon", "banana", "bandage", "barrel", "baseball",
  "basket", "basketball", "bathtub", "battery", "beach ball", "bed", "bell", "belt",
  "bench", "bicycle", "blanket", "blender", "boat", "bone", "book", "bookshelf",
  "boot", "bottle", "bow tie", "bowl", "box", "bracelet", "bread", "brick",
  "bridge", "briefcase", "broom", "brush", "bubble", "bucket", "building",
  "bus", "butterfly", "button", "cabinet", "cable", "cactus", "cage", "cake",
  "calculator", "calendar", "camera", "campfire", "candle", "candy", "canoe",
  "car", "card", "carpet", "carrot", "cart", "castle", "cat", "ceiling fan",
  "cell phone", "chain", "chair", "chalk", "chandelier", "cheese", "cherry",
  "chest", "chicken", "chimney", "chocolate", "chopsticks", "church", "clock",
  "cloud", "coat", "coconut", "coffee", "coin", "comb", "compass", "computer",
  "cone", "cookie", "couch", "cow", "crab", "crayon", "credit card", "croissant",
  "crown", "cup", "curtain", "cushion", "dart", "diamond", "dice", "dinosaur",
  "dish", "dog", "doll", "dolphin", "domino", "donut", "door", "doorbell",
  "dragon", "drawer", "dress", "drill", "drum", "duck", "dumbbell", "ear",
  "earring", "egg", "eggplant", "elbow", "elephant", "elevator", "envelope",
  "eraser", "escalator", "eye", "eyebrow", "eyeglasses", "face", "fan", "faucet",
  "feather", "fence", "finger", "fire", "fire hydrant", "firework", "fish",
  "fishing rod", "flag", "flame", "flashlight", "flip flop", "floor", "flower",
  "flute", "fly", "folder", "foot", "football", "fork", "fountain", "fox",
  "frame", "french fries", "fridge", "frog", "frying pan", "garage", "garden",
  "garlic", "gate", "ghost", "gift", "giraffe", "glass", "globe", "glove",
  "goat", "gold", "golf ball", "gorilla", "grapes", "grass", "grill", "guitar",
  "hair", "hamburger", "hammer", "hammock", "hand", "handbag", "handcuffs",
  "hanger", "hat", "headphones", "heart", "helicopter", "helmet", "hippo",
  "hockey stick", "hole", "honey", "hook", "horn", "horse", "horseshoe",
  "hospital", "hot dog", "hotel", "hourglass", "house", "ice cream", "ice cube",
  "igloo", "iron", "island", "jacket", "jar", "jeans", "jellyfish", "jet",
  "jewelry", "kangaroo", "ketchup", "kettle", "key", "keyboard", "kite",
  "kitten", "knee", "knife", "knot", "ladder", "ladybug", "lake", "lamp",
  "laptop", "leaf", "leg", "lemon", "letter", "lettuce", "library", "light bulb",
  "lighter", "lightning", "lion", "lips", "lipstick", "lizard", "lobster",
  "lock", "lollipop", "luggage", "magnet", "mailbox", "map", "marker",
  "marshmallow", "mask", "match", "medal", "melon", "menu", "mermaid",
  "microphone", "microscope", "microwave", "milk", "mirror", "mitten", "money",
  "monkey", "moon", "mop", "mosquito", "motorcycle", "mountain", "mouse",
  "mousetrap", "mouth", "muffin", "mug", "mushroom", "nail", "necklace",
  "needle", "nest", "net", "newspaper", "nose", "notebook", "nut", "ocean",
  "octopus", "onion", "orange", "oven", "owl", "paddle", "paint", "paintbrush",
  "palm tree", "pan", "pancake", "panda", "pants", "paper", "paper clip",
  "parachute", "parrot", "passport", "pasta", "path", "paw", "pea", "peach",
  "peacock", "peanut", "pear", "pearl", "pen", "pencil", "penguin", "pepper",
  "perfume", "phone", "piano", "pickle", "pie", "pig", "pillow", "pin",
  "pineapple", "pipe", "pirate", "pizza", "plant", "plate", "plug", "plum",
  "pocket", "polar bear", "pool", "popcorn", "popsicle", "postcard", "pot",
  "potato", "present", "pretzel", "printer", "pumpkin", "puppy", "purse",
  "puzzle", "pyramid", "rabbit", "raccoon", "racket", "radio", "rain",
  "rainbow", "rake", "raspberry", "rat", "rectangle", "remote control", "ribbon",
  "rice", "ring", "river", "road", "robot", "rock", "rocket", "roof",
  "rope", "rose", "rug", "ruler", "safe", "sailboat", "salt", "sand", "sandal",
  "sandwich", "satellite", "sauce", "sausage", "saw", "saxophone", "scale",
  "scarf", "school", "scissors", "scooter", "scorpion", "screw", "screwdriver",
  "seahorse", "seal", "seashell", "shark", "sheep", "shelf", "shell", "shield",
  "ship", "shirt", "shoe", "shopping cart", "shovel", "shower", "shrimp",
  "sign", "sink", "skateboard", "skeleton", "ski", "skirt", "skull", "skunk",
  "skyscraper", "sled", "slide", "slippers", "sloth", "smoke", "snail", "snake",
  "sneaker", "snow", "snowflake", "snowman", "soap", "soccer ball", "sock",
  "sofa", "soup", "spatula", "speaker", "spider", "spoon", "spring", "square",
  "squid", "squirrel", "stadium", "stairs", "stamp", "stapler", "star",
  "statue", "steak", "steering wheel", "stick", "stop sign", "stove",
  "strawberry", "street", "string", "submarine", "sugar", "suitcase", "sun",
  "sunflower", "sunglasses", "surfboard", "swan", "sweater", "swimming pool",
  "swing", "sword", "table", "taco", "tail", "tank", "tape", "target", "taxi",
  "tea", "teapot", "teddy bear", "telephone", "telescope", "television",
  "tennis ball", "tent", "thermometer", "thread", "throne", "thumb", "thunder",
  "ticket", "tie", "tiger", "tire", "tissue", "toast", "toaster", "toe",
  "toilet", "tomato", "tongue", "toolbox", "tooth", "toothbrush", "toothpaste",
  "top hat", "torch", "tornado", "tortoise", "towel", "tower", "toy", "tractor",
  "traffic light", "train", "trampoline", "trash can", "treasure", "tree",
  "triangle", "tricycle", "trophy", "truck", "trumpet", "trunk", "tulip",
  "turkey", "turtle", "tuxedo", "umbrella", "unicorn", "van", "vase", "vest",
  "violin", "volcano", "volleyball", "waffle", "wagon", "wall", "wallet",
  "wardrobe", "washing machine", "watch", "water", "waterfall", "watermelon",
  "wave", "web", "wedding cake", "whale", "wheel", "wheelbarrow", "whistle",
  "wig", "windmill", "window", "wine", "wing", "wizard", "wolf", "worm",
  "wrench", "yacht", "yarn", "yogurt", "zebra", "zipper", "zoo"
];

const actions = [
  "arm wrestling", "baking", "balancing", "barking", "bathing", "biking", "biting",
  "blinking", "blowing", "blushing", "boating", "bowing", "boxing", "breakdancing",
  "breathing", "brushing teeth", "building", "burping", "camping", "catching",
  "celebrating", "chasing", "cheering", "chewing", "choking", "chopping", "clapping",
  "cleaning", "climbing", "cooking", "coughing", "counting", "crawling", "crying",
  "cutting", "cycling", "dancing", "daydreaming", "digging", "diving", "drawing",
  "dreaming", "drinking", "driving", "drumming", "eating", "exercising", "falling",
  "farming", "fighting", "fishing", "floating", "flying", "folding", "frowning",
  "gardening", "giggling", "golfing", "grabbing", "grilling", "growing", "guessing",
  "hammering", "hanging", "hiding", "high fiving", "hiking", "hitting", "holding",
  "hopping", "hugging", "humming", "hunting", "ice skating", "ironing", "itching",
  "jogging", "juggling", "jumping", "jumping rope", "kayaking", "kicking", "kissing",
  "kneeling", "knitting", "laughing", "leaning", "leaping", "licking", "lifting",
  "listening", "looking", "marching", "meditating", "melting", "mopping", "moving",
  "napping", "nodding", "painting", "parking", "peeking", "peeling", "petting",
  "picking", "planting", "playing cards", "playing chess", "playing guitar",
  "playing piano", "pointing", "poking", "popping", "posing", "pouring", "pouting",
  "praying", "pulling", "punching", "pushing", "racing", "raining", "raking",
  "reading", "relaxing", "riding", "ripping", "roasting", "rock climbing", "rocking",
  "roller skating", "rolling", "rowing", "running", "sailing", "saluting", "sawing",
  "screaming", "scuba diving", "sewing", "shaking", "shaving", "shopping", "shoveling",
  "showering", "shrugging", "singing", "sipping", "sitting", "skateboarding",
  "skating", "skiing", "skipping", "skydiving", "slapping", "sleeping", "sliding",
  "smelling", "smiling", "sneezing", "snoring", "snowboarding", "spinning",
  "spitting", "splashing", "sprinting", "squatting", "standing", "staring",
  "steering", "stomping", "stretching", "studying", "sucking", "sunbathing",
  "surfing", "sweating", "sweeping", "swimming", "swinging", "talking", "tanning",
  "tap dancing", "tasting", "teaching", "texting", "thinking", "throwing",
  "tickling", "tossing", "touching", "tripping", "tumbling", "turning", "twirling",
  "typing", "vacuuming", "voting", "waddling", "waiting", "waking up", "walking",
  "washing", "watching", "waving", "weighing", "weightlifting", "whispering",
  "whistling", "winking", "winning", "wiping", "working", "wrapping", "wrestling",
  "writing", "yawning", "yelling", "zipping"
];

const phrases = [
  "bad hair", "bank robbery", "beach party", "bear hug", "belly flop", "best friend",
  "big foot", "birthday party", "black eye", "blind date", "board game", "book worm",
  "brain freeze", "bubble bath", "bus stop", "camp fire", "car wash", "card game",
  "cat nap", "cell phone", "cheese burger", "chicken wings", "city skyline", "clean slate",
  "coffee break", "cold feet", "couch potato", "day dream", "dead end", "disco ball",
  "dog house", "door bell", "double dutch", "dream team", "drive thru", "easy peasy",
  "elbow room", "eye contact", "face palm", "face time", "fake news", "fast food",
  "field trip", "finger food", "fire drill", "first place", "fish tank", "fist bump",
  "flash mob", "flat tire", "flea market", "food fight", "french kiss", "front door",
  "fruit salad", "full moon", "game night", "ghost story", "girl scout", "gold fish",
  "good luck", "goose bumps", "green thumb", "group hug", "gummy bear", "gym class",
  "hair cut", "half time", "hand shake", "happy hour", "head start", "heart beat",
  "heavy metal", "high five", "hip hop", "home run", "homework", "honey moon",
  "horror movie", "horse back", "hot air", "hot chocolate", "hot sauce", "hot tub",
  "house party", "ice age", "ice cream", "ice cube", "ice rink", "jelly bean",
  "jet lag", "jump rope", "junk food", "karate chop", "key chain", "kick back",
  "king size", "knee cap", "knock knock", "lap top", "lawn mower", "lazy boy",
  "lemon drop", "life guard", "light switch", "lip gloss", "living room", "log cabin",
  "long jump", "loud mouth", "love letter", "lunch box", "mad scientist", "magic trick",
  "mail man", "marshmallow", "milk shake", "monkey bars", "moon light", "morning coffee",
  "movie star", "mud pie", "music box", "nail polish", "name tag", "night owl",
  "no way", "nose dive", "nut cracker", "old school", "one way", "open door",
  "orange juice", "paint ball", "paper cut", "paper plane", "parking lot", "peace sign",
  "peanut butter", "pencil case", "pet shop", "phone call", "photo bomb", "piano keys",
  "picnic table", "pillow fight", "ping pong", "pizza party", "plant pot", "play date",
  "pogo stick", "polar bear", "pool party", "pop corn", "pop quiz", "post office",
  "potato chip", "power nap", "pretty please", "prom night", "rain coat", "rain drop",
  "road trip", "rock band", "rock star", "roller coaster", "roof top", "rubber duck",
  "running late", "rush hour", "sad face", "safe zone", "sand box", "sand castle",
  "school bus", "science fair", "screen time", "sea food", "sea shell", "selfie stick",
  "shoe lace", "shopping bag", "short cut", "show time", "side walk", "silly string",
  "ski lift", "slap stick", "sleep over", "sleeping bag", "slow motion", "smart phone",
  "smile face", "snack time", "snow angel", "snow ball", "snow globe", "snow man",
  "soap bubble", "soda can", "space ship", "spare tire", "speed bump", "spin class",
  "spit ball", "spring break", "stage fright", "star fish", "stay home", "stop sign",
  "story time", "street food", "sun burn", "sun glasses", "sun rise", "sun set",
  "super hero", "super star", "sweet dreams", "sweet tooth", "swim suit", "table tennis",
  "tag team", "tail spin", "take out", "tall tale", "tea party", "team work",
  "teddy bear", "text message", "thank you", "theme park", "thumb war", "thunder storm",
  "time out", "toe nail", "tooth fairy", "top secret", "touch down", "toy box",
  "tree house", "triple jump", "tug war", "tv show", "twin sister", "upper cut",
  "video game", "wake up", "walk out", "war zone", "water balloon", "water bottle",
  "water gun", "water park", "water slide", "wave pool", "weather man", "wedding day",
  "whale shark", "wheel chair", "white house", "wild west", "wind mill", "window seat",
  "winter break", "wish list", "witch hat", "work out", "yoga mat", "zip line",
  "zoo keeper"
];

const popCulture = [
  "Adele", "Ariana Grande", "Avatar", "Barbie", "Batman", "Beyonce", "Bruno Mars",
  "Captain America", "Cinderella", "Deadpool", "Disney", "Dora", "Drake", "Ed Sheeran",
  "Elmo", "Elsa", "Elvis", "Eminem", "Finding Nemo", "Fortnite", "Frozen", "Godzilla",
  "Groot", "Harry Potter", "Hello Kitty", "Hulk", "Iron Man", "James Bond",
  "Justin Bieber", "Katy Perry", "Lady Gaga", "Lego", "Lion King", "Mario",
  "Mickey Mouse", "Minecraft", "Minions", "Moana", "Monopoly", "Mr. Bean", "Nemo",
  "Nike", "Nintendo", "Olaf", "Pac-Man", "Peppa Pig", "Pikachu", "Pokemon", "Rapunzel",
  "Rihanna", "Scooby Doo", "Shakira", "Shrek", "Simpsons", "Snow White", "Sonic",
  "Spider-Man", "SpongeBob", "Star Wars", "Super Mario", "Superman", "Taylor Swift",
  "Teenage Mutant", "The Beatles", "The Grinch", "The Rock", "Thor", "TikTok",
  "Toy Story", "Tweety Bird", "Uber", "Wall-E", "Willy Wonka", "Winnie Pooh",
  "Wonder Woman", "X-Men", "Yoda", "YouTube", "Zelda", "Zumba",
  "Netflix", "Amazon", "Apple", "Google", "Facebook", "Instagram", "Snapchat",
  "Spotify", "Tesla", "McDonalds", "Starbucks", "Coca Cola", "Adidas", "PlayStation",
  "Xbox", "Costco", "Target", "Walmart", "Netflix", "Pepsi", "Oreo", "Doritos",
  "Skittles", "M&Ms", "Gatorade", "Red Bull", "Nutella", "Cheerios", "Frosted Flakes"
];

const places = [
  "Africa", "Alaska", "Amazon", "Amsterdam", "Antarctica", "Arizona", "Asia",
  "Australia", "Bahamas", "Bali", "Bangkok", "Barcelona", "Beach", "Beijing",
  "Berlin", "Boston", "Brazil", "California", "Canada", "Caribbean", "Chicago",
  "China", "Colorado", "Costa Rica", "Cuba", "Denmark", "Dubai", "Egypt",
  "England", "Europe", "Fiji", "Finland", "Florida", "France", "Germany",
  "Grand Canyon", "Greece", "Greenland", "Hawaii", "Hollywood", "Hong Kong",
  "Iceland", "India", "Indonesia", "Ireland", "Israel", "Italy", "Jamaica",
  "Japan", "Kenya", "Korea", "Las Vegas", "London", "Los Angeles", "Madrid",
  "Maldives", "Manhattan", "Maui", "Mexico", "Miami", "Monaco", "Morocco",
  "Moscow", "Mount Everest", "Nepal", "Netherlands", "New Orleans", "New York",
  "New Zealand", "Nigeria", "North Pole", "Norway", "Ohio", "Pacific Ocean",
  "Paris", "Peru", "Philippines", "Poland", "Portugal", "Rome", "Russia",
  "San Diego", "San Francisco", "Scotland", "Seattle", "Seoul", "Shanghai",
  "Singapore", "South Africa", "South Pole", "Spain", "Sweden", "Switzerland",
  "Sydney", "Texas", "Thailand", "Times Square", "Tokyo", "Toronto", "Turkey",
  "Vatican", "Venice", "Vienna", "Vietnam", "Washington DC", "Yellowstone"
];

const foodAndDrink = [
  "apple juice", "apple pie", "avocado", "bacon", "bagel", "banana", "barbecue",
  "birthday cake", "biscuit", "blueberry", "bread", "broccoli", "brownie", "burger",
  "burrito", "butter", "cake", "candy", "caramel", "carrot", "cereal", "cheese",
  "cheesecake", "cherry", "chicken", "chips", "chocolate", "cinnamon", "coconut",
  "coffee", "cookie", "corn", "cotton candy", "cracker", "cream", "croissant",
  "cupcake", "donut", "egg", "fish", "french fries", "fried chicken", "fried rice",
  "fruit", "garlic", "grape", "grapefruit", "gravy", "green bean", "grilled cheese",
  "guacamole", "gummy bear", "ham", "hamburger", "honey", "hot chocolate", "hot dog",
  "ice cream", "ice tea", "jam", "jelly", "juice", "ketchup", "kiwi", "lasagna",
  "lemon", "lemonade", "lettuce", "lime", "lobster", "mac cheese", "mango",
  "maple syrup", "marshmallow", "mashed potato", "meat", "meatball", "milk",
  "milkshake", "muffin", "mushroom", "mustard", "nachos", "noodles", "olive",
  "omelette", "onion", "orange", "orange juice", "pancake", "pasta", "peach",
  "peanut", "peanut butter", "pear", "pepper", "pepperoni", "pickle", "pie",
  "pineapple", "pizza", "plum", "popcorn", "pork", "potato", "pretzel", "pudding",
  "pumpkin", "raisin", "raspberry", "rice", "salad", "salmon", "salsa", "sandwich",
  "sausage", "shrimp", "smoothie", "soda", "soup", "spaghetti", "spinach", "steak",
  "strawberry", "sugar", "sushi", "syrup", "taco", "toast", "tofu", "tomato",
  "turkey", "vanilla", "vegetable", "waffle", "walnut", "watermelon", "whipped cream",
  "yogurt"
];

const everyday = [
  "alarm", "allowance", "alphabet", "anniversary", "apartment", "apology", "applause",
  "attic", "babysitter", "backyard", "balance", "bandaid", "basement", "bathroom",
  "battery", "bedroom", "bedtime", "believer", "bicycle", "birthday", "blanket",
  "blindfold", "breakfast", "brother", "bubble", "buddy", "calendar", "cartoon",
  "celebration", "champion", "checklist", "childhood", "chore", "classroom",
  "collection", "commercial", "compliment", "conversation", "costume", "countdown",
  "cousin", "crosswalk", "cubicle", "curfew", "customer", "dad", "daughter",
  "deadline", "decision", "dentist", "dessert", "diary", "dinner", "directions",
  "discount", "divorce", "doctor", "doorway", "download", "downtown", "driveway",
  "email", "emergency", "employee", "entrance", "errand", "escalator", "evening",
  "excuse", "exercise", "exit", "family", "farmer", "father", "favorite", "feeling",
  "festival", "firefighter", "flashback", "flu", "folder", "forecast", "forever",
  "freedom", "freezer", "friend", "friendship", "furniture", "garage", "garbage",
  "generation", "goal", "goodbye", "grade", "grandma", "grandpa", "grocery",
  "groundhog", "guest", "haircut", "hallway", "handwriting", "hangover", "headache",
  "headline", "heartbreak", "hello", "helper", "hero", "hiccup", "highlight",
  "hobby", "holiday", "homework", "honesty", "husband", "idea", "imagination",
  "interview", "invitation", "jealousy", "joke", "journey", "kindness", "kitchen",
  "landlord", "laundry", "lesson", "lifetime", "living room", "locker", "lunchtime",
  "manager", "marriage", "meeting", "memory", "message", "midnight", "mistake",
  "mom", "moment", "money", "morning", "mother", "mystery", "nap", "napkin",
  "neighbor", "nephew", "nickname", "nightmare", "niece", "nurse", "office",
  "opinion", "opportunity", "outside", "overtime", "owner", "package", "pajamas",
  "parent", "password", "patience", "payment", "permission", "personality", "photo",
  "picture", "playground", "police", "president", "principal", "privacy", "problem",
  "promise", "question", "receipt", "recipe", "relationship", "reminder", "rent",
  "report", "restaurant", "reunion", "reward", "ringtone", "roommate", "routine",
  "salary", "savings", "schedule", "secret", "semester", "sibling", "signature",
  "silence", "sister", "sleepover", "smartphone", "snack", "solution", "son",
  "sorry", "spelling", "stranger", "student", "sunrise", "sunset", "surprise",
  "talent", "teacher", "teenager", "temper", "test", "text", "therapy", "tip",
  "toddler", "tomorrow", "tonight", "tradition", "traffic", "trouble", "truth",
  "tutor", "uncle", "uniform", "upgrade", "username", "vacation", "valentine",
  "vending machine", "visitor", "vitamin", "voicemail", "volunteer", "warning",
  "weather", "wedding", "weekend", "welcome", "wife", "wish", "worry", "yesterday"
];

export const allWords: string[] = [
  ...commonObjects,
  ...actions,
  ...phrases,
  ...popCulture,
  ...places,
  ...foodAndDrink,
  ...everyday,
];

export function getRandomWord(usedWords: Set<string>): string {
  const availableWords = allWords.filter(word => !usedWords.has(word));
  if (availableWords.length === 0) {
    return allWords[Math.floor(Math.random() * allWords.length)];
  }
  return availableWords[Math.floor(Math.random() * availableWords.length)];
}

export function shuffleWords(): string[] {
  const shuffled = [...allWords];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}
